#pragma once

#define PERMISSIVE_HOLD
#define TAPPING_TERM 350
///#define ACHORDION_STREAK 220
//#define TAPPING_TERM_PER_KEY 
#define DYNAMIC_KEYMAP_LAYER_COUNT 16
#define VIAL_KEYBOARD_UID {0x89, 0x36, 0x2A, 0xC7, 0xFA, 0xD8, 0x89, 0x45}
#define VIAL_UNLOCK_COMBO_ROWS {0, 0}
#define VIAL_UNLOCK_COMBO_COLS {0, 1}
